### ISSUE TITLE
你好，我正在做一个mac版机器人

### ISSUE THREAD

**Issue by hjackguo** [alexiscn/HuobiMac#1]
你好，我在哈希加密一块遇到问题，希望能看看你软件中如何处理哈希加密一块的内容。方便加一下您的微信或者qq吗？十分感谢

**Comment by alexiscn** [comment]
Just use CommonCrypto... What is your actual problem？

**Comment by alexiscn** [comment]
Please refer to [HuobiAPISignature.swift](https://github.com/alexiscn/HuobiMac/blob/master/DevelopmentPods/HuobiSwift/HuobiAPISignature.swift) . I have checked the signature code is correctly calculated.

**Comment by hjackguo** [comment]
Thanks.
